name: Initiate tests on opam and '-installer' repositories

on:
  workflow_dispatch:

jobs:
  github-notify:
    strategy:
      fail-fast: true
      matrix:
        # repository
        #    [HOST/]OWNER/REPO format
        include:
        - repository: diskuv/dkml-installer-ocaml
          yml: package.yml
        - repository: diskuv/dkml-component-opam
          yml: asset.yml
    runs-on: ubuntu-latest
    steps:
      - name: POST workflow dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.TRIGGER_DKML_INSTALLER_OCAML }}
        run: |
          set -x && gh workflow --repo "${{matrix.repository}}" run ${{matrix.yml}} -f diskuv-opam-repository=${GITHUB_SHA}
