test:
  extends:
    - .alpine:before-sphinx
  stage: test
  script:
  - echo Building Sphinx html twice so that Sphinx cross-references work ...
  - make -C contributors html ; make -C contributors html O="-W"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

.installer-unix:
  artifacts:
    untracked: false
    when: always
    expire_in: "30 days"
    paths:
      - dkml-native-*.tar.gz
      - build/pkg/bump/.ci/o/log
      - build/pkg/bump/*/sw/logs

installer-windows_x86_64:
  extends:
    - .windows:before-script-shared-setupmachine
  stage: build
  allow_failure: true # Needs more than 2 hours, which is GitLab SaaS limit as of 2023-11-24. See https://gitlab.com/groups/gitlab-org/-/epics/2162
  timeout: 3h
  artifacts:
    untracked: false
    when: always
    expire_in: "30 days"
    paths:
      - C:/build/pkg/bump/.ci/o/*/share/dkml-installer-ocaml-*/t
      - C:/build/pkg/bump/.ci/o/log
      - C:/build/pkg/bump/*/sw/logs
  script:
  # Identity for dkml-compiler git-based patches
  - git config --global user.email "anyone@example.com"

  - cmake --preset ci-reproduce-windows-c -G Ninja
  - cmake --build --preset ci-reproduce-windows-c

  - copy C:/build/pkg/bump/.ci/o/*/share/dkml-installer-ocaml-*/t/unsigned-dkml-native-windows_x86_64-*.exe .

installer-debian_x86_64: # Debian is just the prototype for Linux with a "modern" libc
  extends:
    - .cmake-with-opam-prereqs-debian:before
    - .installer-unix
  stage: build
  script:
  # Identity for dkml-compiler git-based patches
  - git config --global user.email "anyone@example.com"

  - .ci/cmake/bin/cmake --preset ci-reproduce -G Ninja -D DKML_HOST_LINUX_DOCKER=0
  - .ci/cmake/bin/cmake --build --preset ci-reproduce

  - ver=$(.ci/cmake/bin/cmake -P cmake/get-version.cmake)
  - build/pkg/bump/.ci/o/$ver/share/dkml-installer-ocaml-network/t/bundle-dkml-native-linux_x86_64-i.sh tar
  - gzip dkml-native-linux_x86_64-i-$ver.tar

installer-darwin_x86_64:
  extends:
    - .cmake-with-opam-prereqs-macos:build
    - .installer-unix
  stage: build
  variables:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
  script:
  # Identity for dkml-compiler git-based patches
  - git config --global user.email "anyone@example.com"

  - .ci/cmake/bin/cmake --preset ci-reproduce -G Ninja -D DKML_HOST_ABI=darwin_x86_64 -D DKML_TARGET_ABI=darwin_x86_64
  - .ci/cmake/bin/cmake --build --preset ci-reproduce

  - ver=$(.ci/cmake/bin/cmake -P cmake/get-version.cmake)
  - build/pkg/bump/.ci/o/$ver/share/dkml-installer-ocaml-network/t/bundle-dkml-native-darwin_x86_64-i.sh tar
  - gzip dkml-native-darwin_x86_64-i-$ver.tar

installer-darwin_arm64:
  extends:
    - .cmake-with-opam-prereqs-macos:build
    - .installer-unix
  stage: build
  variables:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
  script:
  # Identity for dkml-compiler git-based patches
  - git config --global user.email "anyone@example.com"

  - .ci/cmake/bin/cmake --preset ci-reproduce -G Ninja -D DKML_HOST_ABI=darwin_arm64 -D DKML_TARGET_ABI=darwin_arm64
  - .ci/cmake/bin/cmake --build --preset ci-reproduce

  - ver=$(.ci/cmake/bin/cmake -P cmake/get-version.cmake)
  - build/pkg/bump/.ci/o/$ver/share/dkml-installer-ocaml-network/t/bundle-dkml-native-darwin_arm64-i.sh tar
  - gzip dkml-native-darwin_arm64-i-$ver.tar

installer-linux_x86_64:
  extends:
    - .linux:setup-dkml-no-matrix
    - .installer-unix
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    # We just need manylinux (some ancient Linux) so that linux_x86_64
    # binaries are portable. All OCaml bits are done by DkSDK.
    PRIMARY_SWITCH_SKIP_INSTALL: 'true'
    SKIP_OPAM_MODIFICATIONS: 'true'
    MANYLINUX: "true"
    DOCKER_TLS_CERTDIR: "/certs"
    dockcross_image_custom_prefix: ""

    dkml_host_os: 'linux'
    opam_root_cacheable: '.ci/o'
    abi_pattern: 'manylinux2014-linux_x86_64'
    comment: '(CentOS 7, etc.)'
    bootstrap_opam_version: '2.2.0-alpha-20221228'
    dkml_host_abi: 'linux_x86_64'
    opam_root: '.ci/o'
    dockcross_image: 'dockcross/manylinux2014-x64'
    dockcross_run_extra_args: '--platform linux/amd64'
    #   Extra packages for ManyLinux (_yum). The _apt is for completeness.
    #   sqlite-devel: needed by dkml-component-staging-desktop-full > conf-sqlite3
    #   libX11-devel: needed by dkml-component-staging-desktop-full > graphics > conf-libX11
    #   pkgconfig: needed by dkml-component-staging-desktop-full > conf-sqlite3 > conf-pkg-config
    #   gcc-c++: needed by mccs > conf-c++
    #   libffi-dev: needed by ctypes-foreign > conf-libffi
    dockcross_packages_apt: 'libsqlite3-dev libx11-dev pkg-config libffi-devel'
    dockcross_packages_yum: 'sqlite-devel libX11-devel pkgconfig gcc-c++ libffi-devel'
    in_docker: 'true'

  stage: build
  dependencies: []
  script:
    - .ci/sd4/opamrun/cmdrun sh ./dk dksdk.cmake.copy QUIET
    - .ci/sd4/opamrun/cmdrun cmake --preset ci-reproduce -G Ninja -D SKIP_CMDRUN=1 -D DKML_HOST_LINUX_DOCKER=0
    - .ci/sd4/opamrun/cmdrun cmake --build --preset ci-reproduce

    - ver=$(.ci/cmake/bin/cmake -P cmake/get-version.cmake)
    - build/pkg/bump/.ci/o/$ver/share/dkml-installer-ocaml-network/t/bundle-dkml-native-linux_x86_64-i.sh tar
    - gzip dkml-native-linux_x86_64-i-$ver.tar

# ------------------------------------------------------------------------
# Tests
# ------------------------------------------------------------------------
#
# Why are these separate from [stage: build]?
# 1. Different paths on different machines means that hardcoded library locations
#    can be tested. For example, ci/test.sh has to use CAML_LD_LIBRARY_PATH
#    to work correctly when the test machine is different from the build machine.
#    That betters simulates real end-user requirements.
# 2. If the build succeeds but the test fails, we have the job artifacts from the
#    build job so we can re-run the tests locally.

test-darwin_arm64:
  extends:
    - .cmake-with-opam-prereqs-macos:build
  needs:
    - job: installer-darwin_arm64
      artifacts: true
  script: sh ci/test.sh darwin_arm64

test-debian_x86_64-on-debian_x86_64:
  extends:
    - .cmake-with-opam-prereqs-debian:before
  stage: test
  needs:
    - job: installer-debian_x86_64
      artifacts: true
  script: sh ci/test.sh linux_x86_64

test-linux_x86_64-on-debian_x86_64:
  extends:
    - .cmake-with-opam-prereqs-debian:before
  stage: test
  needs:
    - job: installer-linux_x86_64
      artifacts: true
  script: sh ci/test.sh linux_x86_64
